---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.4
  - name: centos-7.0
  - name: debian-7.8
  - name: fedora-19
  - name: windows-2012r2
    driver:
      gui: true
      box: opentable/win-2012r2-standard-amd64-nocm
      customize:
        vram: 64
suites:
  - name: default
    run_list:
      - recipe[al_agents::default]
    # attributes:
    #   al_agents:
    #     agent:
    #       registration_key: 'your_key_here'
