language: ruby
bundler_args: "--without development"
script:
- bundle exec rubocop .
- bundle exec foodcritic -f any . --tags ~FC109
- bundle exec rspec spec
rvm:
- 2.3.1
gemfile:
- Gemfile
install:
before_install:
# This fixes https://github.com/rubygems/rubygems/issues/2213
before_install:
- gem update --system 2.7.5 
- gem --version
branches:
  only:
  - master
