language: ruby
bundler_args: "--without development"
script:
- bundle exec rubocop .
- bundle exec foodcritic -f any .
- bundle exec rspec spec
rvm:
- 2.3.1
gemfile:
- Gemfile
install:
# This fixes https://github.com/rubygems/rubygems/issues/2213
- sudo gem update --system 2.7.5
branches:
  only:
  - master
