language: ruby
bundler_args: "--without development"
script:
- bundle exec rubocop .
- bundle exec foodcritic -f any .
- bundle exec rspec spec
rvm:
- 2.3.1
gemfile:
- Gemfile
branches:
  only:
  - master
